export { Logo } from './Logo';
export { Close } from './Close';
export { Burger } from './Burger';
export { VK } from './VK';
export { Facebook } from './Facebook';
export { Twitter } from './Twitter';
export { Insta } from './Insta';
export { ArrowRight } from './ArrowRight';
export { ArrowLeft } from './ArrowLeft';
